<?php
include"vendor/autoload.php";
use Public\Product;
use Core\BookProduct;
use Core\NotebookProduct;
use Core\PhoneProduct;
use App\AsusProduct;
use App\AppleProduct;
use App\LenovoProduct;
use App\SumsungProduct;
$product = new Product();
$product->setName('Asus');
$product->setColl(10);
var_dump($product->getColl());
var_dump($product->getName());
echo "<br>";
$note = new NotebookProduct();
$note->setColl(2);
$note->setPrice(100);
var_dump($note->getPrice());
var_dump($note->getCheck());
echo "<br>";
$book = new BookProduct();
$book->setColl(13);
$book->setPage(100);
var_dump($book->getPage());
var_dump($book->sumPage());
echo "<br>";
$phone = new PhoneProduct();
$phone->setColl(132);
$phone->setRam(12);
var_dump($phone->getRam());
var_dump($phone->getCollRam());
echo "<br>";
$sumsung = new SumsungProduct();
$sumsung->setCpu(2);
var_dump($sumsung->getCpu());
$sumsung->setRam(8);